// This file is generated by Slice Machine. Update with care!

import ContactDandeForm from './ContactDandeForm';
import HeroSlice from './HeroSlice';
import HeroTwo from './HeroTwo';
import LogoList from './LogoList';
import Primary from './Primary';
import RowOfCards from './RowOfCards';
import RowOfItems from './RowOfItems';

export {
	ContactDandeForm,
	HeroSlice,
	HeroTwo,
	LogoList,
	Primary,
	RowOfCards,
	RowOfItems,
};

export const components = {
	contact_dande_form: ContactDandeForm,
	hero_slice: HeroSlice,
	hero_two: HeroTwo,
	logo_list: LogoList,
	primary: Primary,
	row_of_cards: RowOfCards,
	row_of_items: RowOfItems,
};
