export const CALCULATOR_INITIALIZE = 'CALCULATOR_INITIALIZE';
export const SET_SENT_TO_COUNTRY = 'SET_SENT_TO_COUNTRY';
export const CALCULATE = 'CALCULATE';
export const SET_IS_FETCHING = 'SET_IS_FETCHING';