// { value: "American Samoa", text: "American Samoa" },
// { value: "Federated States Of Micronesia", text: "Federated States Of Micronesia" },

export const usStates = [
  { value: "Alabama", text: "Alabama" },
  { value: "Alaska", text: "Alaska" },
  { value: "Arizona", text: "Arizona" },
  { value: "Arkansas", text: "Arkansas" },
  { value: "California", text: "California" },
  { value: "Colorado", text: "Colorado" },
  { value: "Connecticut", text: "Connecticut" },
  { value: "Delaware", text: "Delaware" },
  { value: "District Of Columbia", text: "District Of Columbia" },
  { value: "Florida", text: "Florida" },
  { value: "Georgia", text: "Georgia" },
  { value: "Guam", text: "Guam" },
  { value: "Hawaii", text: "Hawaii" },
  { value: "Idaho", text: "Idaho" },
  { value: "Illinois", text: "Illinois" },
  { value: "Indiana", text: "Indiana" },
  { value: "Iowa", text: "Iowa" },
  { value: "Kansas", text: "Kansas" },
  { value: "Kentucky", text: "Kentucky" },
  { value: "Louisiana", text: "Louisiana" },
  { value: "Maine", text: "Maine" },
  { value: "Marshall Islands", text: "Marshall Islands" },
  { value: "Maryland", text: "Maryland" },
  { value: "Massachusetts", text: "Massachusetts" },
  { value: "Michigan", text: "Michigan" },
  { value: "Minnesota", text: "Minnesota" },
  { value: "Mississippi", text: "Mississippi" },
  { value: "Missouri", text: "Missouri" },
  { value: "Montana", text: "Montana" },
  { value: "Nebraska", text: "Nebraska" },
  { value: "Nevada", text: "Nevada" },
  { value: "New Hampshire", text: "New Hampshire" },
  { value: "New Jersey", text: "New Jersey" },
  { value: "New Mexico", text: "New Mexico" },
  { value: "New York", text: "New York" },
  { value: "North Carolina", text: "North Carolina" },
  { value: "North Dakota", text: "North Dakota" },
  { value: "Northern Mariana Islands", text: "Northern Mariana Islands" },
  { value: "Ohio", text: "Ohio" },
  { value: "Oklahoma", text: "Oklahoma" },
  { value: "Oregon", text: "Oregon" },
  { value: "Palau", text: "Palau" },
  { value: "Pennsylvania", text: "Pennsylvania" },
  { value: "Puerto Rico", text: "Puerto Rico" },
  { value: "Rhode Island", text: "Rhode Island" },
  { value: "South Carolina", text: "South Carolina" },
  { value: "South Dakota", text: "South Dakota" },
  { value: "Tennessee", text: "Tennessee" },
  { value: "Texas", text: "Texas" },
  { value: "Utah", text: "Utah" },
  { value: "Vermont", text: "Vermont" },
  { value: "Virgin Islands", text: "Virgin Islands" },
  { value: "Virginia", text: "Virginia" },
  { value: "Washington", text: "Washington" },
  { value: "West Virginia", text: "West Virginia" },
  { value: "Wisconsin", text: "Wisconsin" },
  { value: "Wyoming", text: "Wyoming" },
];

export const usStatesAndCities = {
  "New York": [
    { value: "Albany", text: "Albany" },
    { value: "Binghamton", text: "Binghamton" },
    { value: "Buffalo", text: "Buffalo" },
    { value: "Freeport", text: "Freeport" },
    { value: "Hempstead", text: "Hempstead" },
    { value: "Mount Vernon", text: "Mount Vernon" },
    { value: "New York", text: "New York" },
    { value: "New Rochelle", text: "New Rochelle" },
    { value: "Niagara Falls", text: "Niagara Falls" },
    { value: "Utica", text: "Utica" },
    { value: "Rochester", text: "Rochester" },
    { value: "Schenectady", text: "Schenectady" },
    { value: "Syracuse", text: "Syracuse" },
    { value: "Troy", text: "Troy" },
    { value: "White Plains", text: "White Plains" },
    { value: "Valley Stream", text: "Valley Stream" },
    { value: "Yonkers", text: "Yonkers" },
  ],
  California: [
    { value: "Los Angeles", text: "Los Angeles" },
    { value: "San Diego", text: "San Diego" },
    { value: "San Jose", text: "San Jose" },
    { value: "San Francisco", text: "San Francisco" },
    { value: "Fresno", text: "Fresno" },
    { value: "Sacramento", text: "Sacramento" },
    { value: "Long Beach", text: "Long Beach" },
    { value: "Oakland", text: "Oakland" },
    { value: "Bakersfield", text: "Bakersfield" },
    { value: "Anaheim", text: "Anaheim" },
    { value: "Santa Ana", text: "Santa Ana" },
    { value: "Riverside", text: "Riverside" },
    { value: "Stockton", text: "Stockton" },
    { value: "Chula Vista", text: "Chula Vista" },
    { value: "Irvine", text: "Irvine" },
    { value: "Fremont", text: "Fremont" },
    { value: "San Bernardino", text: "San Bernardino" },
    { value: "Modesto", text: "Modesto" },
    { value: "Fontana", text: "Fontana" },
    { value: "Oxnard", text: "Oxnard" },
    { value: "Moreno Valley", text: "Moreno Valley" },
    { value: "Huntington Beach", text: "Huntington Beach" },
    { value: "Glendale", text: "Glendale" },
    { value: "Santa Clarita", text: "Santa Clarita" },
    { value: "Garden Grove", text: "Garden Grove" },
    { value: "Oceanside", text: "Oceanside" },
    { value: "Rancho Cucamonga", text: "Rancho Cucamonga" },
    { value: "Santa Rosa", text: "Santa Rosa" },
    { value: "Ontario", text: "Ontario" },
    { value: "Lancaster", text: "Lancaster" },
    { value: "Elk Grove", text: "Elk Grove" },
    { value: "Corona", text: "Corona" },
    { value: "Palmdale", text: "Palmdale" },
    { value: "Salinas", text: "Salinas" },
    { value: "Pomona", text: "Pomona" },
    { value: "Hayward", text: "Hayward" },
    { value: "Escondido", text: "Escondido" },
    { value: "Torrance", text: "Torrance" },
    { value: "Sunnyvale", text: "Sunnyvale" },
    { value: "Orange", text: "Orange" },
    { value: "Fullerton", text: "Fullerton" },
    { value: "Pasadena", text: "Pasadena" },
    { value: "Thousand Oaks", text: "Thousand Oaks" },
    { value: "Visalia", text: "Visalia" },
    { value: "Simi Valley", text: "Simi Valley" },
    { value: "Concord", text: "Concord" },
    { value: "Roseville", text: "Roseville" },
    { value: "Victorville", text: "Victorville" },
    { value: "Santa Clara", text: "Santa Clara" },
    { value: "Vallejo", text: "Vallejo" },
    { value: "Berkeley", text: "Berkeley" },
    { value: "El Monte", text: "El Monte" },
    { value: "Downey", text: "Downey" },
    { value: "Costa Mesa", text: "Costa Mesa" },
    { value: "Inglewood", text: "Inglewood" },
    { value: "Carlsbad", text: "Carlsbad" },
    { value: "San Buenaventura (Ventura)", text: "San Buenaventura (Ventura)" },
    { value: "Fairfield", text: "Fairfield" },
    { value: "West Covina", text: "West Covina" },
    { value: "Murrieta", text: "Murrieta" },
    { value: "Richmond", text: "Richmond" },
    { value: "Norwalk", text: "Norwalk" },
    { value: "Antioch", text: "Antioch" },
    { value: "Temecula", text: "Temecula" },
    { value: "Burbank", text: "Burbank" },
    { value: "Daly City", text: "Daly City" },
    { value: "Rialto", text: "Rialto" },
    { value: "Santa Maria", text: "Santa Maria" },
    { value: "El Cajon", text: "El Cajon" },
    { value: "San Mateo", text: "San Mateo" },
    { value: "Clovis", text: "Clovis" },
    { value: "Compton", text: "Compton" },
    { value: "Jurupa Valley", text: "Jurupa Valley" },
    { value: "Vista", text: "Vista" },
    { value: "South Gate", text: "South Gate" },
    { value: "Mission Viejo", text: "Mission Viejo" },
    { value: "Vacaville", text: "Vacaville" },
    { value: "Carson", text: "Carson" },
    { value: "Hesperia", text: "Hesperia" },
    { value: "Santa Monica", text: "Santa Monica" },
    { value: "Westminster", text: "Westminster" },
    { value: "Redding", text: "Redding" },
    { value: "Santa Barbara", text: "Santa Barbara" },
    { value: "Chico", text: "Chico" },
    { value: "Newport Beach", text: "Newport Beach" },
    { value: "San Leandro", text: "San Leandro" },
    { value: "San Marcos", text: "San Marcos" },
    { value: "Whittier", text: "Whittier" },
    { value: "Hawthorne", text: "Hawthorne" },
    { value: "Citrus Heights", text: "Citrus Heights" },
    { value: "Tracy", text: "Tracy" },
    { value: "Alhambra", text: "Alhambra" },
    { value: "Livermore", text: "Livermore" },
    { value: "Buena Park", text: "Buena Park" },
    { value: "Menifee", text: "Menifee" },
    { value: "Hemet", text: "Hemet" },
    { value: "Lakewood", text: "Lakewood" },
    { value: "Merced", text: "Merced" },
    { value: "Chino", text: "Chino" },
    { value: "Indio", text: "Indio" },
    { value: "Redwood City", text: "Redwood City" },
    { value: "Lake Forest", text: "Lake Forest" },
    { value: "Napa", text: "Napa" },
    { value: "Tustin", text: "Tustin" },
    { value: "Bellflower", text: "Bellflower" },
    { value: "Mountain View", text: "Mountain View" },
    { value: "Chino Hills", text: "Chino Hills" },
    { value: "Baldwin Park", text: "Baldwin Park" },
    { value: "Alameda", text: "Alameda" },
    { value: "Upland", text: "Upland" },
    { value: "San Ramon", text: "San Ramon" },
    { value: "Folsom", text: "Folsom" },
    { value: "Pleasanton", text: "Pleasanton" },
    { value: "Union City", text: "Union City" },
    { value: "Perris", text: "Perris" },
    { value: "Manteca", text: "Manteca" },
    { value: "Lynwood", text: "Lynwood" },
    { value: "Apple Valley", text: "Apple Valley" },
    { value: "Redlands", text: "Redlands" },
    { value: "Turlock", text: "Turlock" },
    { value: "Milpitas", text: "Milpitas" },
    { value: "Redondo Beach", text: "Redondo Beach" },
    { value: "Rancho Cordova", text: "Rancho Cordova" },
    { value: "Yorba Linda", text: "Yorba Linda" },
    { value: "Palo Alto", text: "Palo Alto" },
    { value: "Davis", text: "Davis" },
    { value: "Camarillo", text: "Camarillo" },
    { value: "Walnut Creek", text: "Walnut Creek" },
    { value: "Pittsburg", text: "Pittsburg" },
    { value: "South San Francisco", text: "South San Francisco" },
    { value: "Yuba City", text: "Yuba City" },
    { value: "San Clemente", text: "San Clemente" },
    { value: "Laguna Niguel", text: "Laguna Niguel" },
    { value: "Pico Rivera", text: "Pico Rivera" },
    { value: "Montebello", text: "Montebello" },
    { value: "Lodi", text: "Lodi" },
    { value: "Madera", text: "Madera" },
    { value: "Santa Cruz", text: "Santa Cruz" },
    { value: "La Habra", text: "La Habra" },
    { value: "Encinitas", text: "Encinitas" },
    { value: "Monterey Park", text: "Monterey Park" },
    { value: "Tulare", text: "Tulare" },
    { value: "Cupertino", text: "Cupertino" },
    { value: "Gardena", text: "Gardena" },
    { value: "National City", text: "National City" },
    { value: "Rocklin", text: "Rocklin" },
    { value: "Petaluma", text: "Petaluma" },
    { value: "Huntington Park", text: "Huntington Park" },
    { value: "San Rafael", text: "San Rafael" },
    { value: "La Mesa", text: "La Mesa" },
    { value: "Arcadia", text: "Arcadia" },
    { value: "Fountain Valley", text: "Fountain Valley" },
    { value: "Diamond Bar", text: "Diamond Bar" },
    { value: "Woodland", text: "Woodland" },
    { value: "Santee", text: "Santee" },
    { value: "Lake Elsinore", text: "Lake Elsinore" },
    { value: "Porterville", text: "Porterville" },
    { value: "Paramount", text: "Paramount" },
    { value: "Eastvale", text: "Eastvale" },
    { value: "Rosemead", text: "Rosemead" },
    { value: "Hanford", text: "Hanford" },
    { value: "Highland", text: "Highland" },
    { value: "Brentwood", text: "Brentwood" },
    { value: "Novato", text: "Novato" },
    { value: "Colton", text: "Colton" },
    { value: "Cathedral City", text: "Cathedral City" },
    { value: "Delano", text: "Delano" },
    { value: "Yucaipa", text: "Yucaipa" },
    { value: "Watsonville", text: "Watsonville" },
    { value: "Placentia", text: "Placentia" },
    { value: "Glendora", text: "Glendora" },
    { value: "Gilroy", text: "Gilroy" },
    { value: "Palm Desert", text: "Palm Desert" },
    { value: "Cerritos", text: "Cerritos" },
    { value: "West Sacramento", text: "West Sacramento" },
    { value: "Aliso Viejo", text: "Aliso Viejo" },
    { value: "Poway", text: "Poway" },
    { value: "La Mirada", text: "La Mirada" },
    { value: "Rancho Santa Margarita", text: "Rancho Santa Margarita" },
    { value: "Cypress", text: "Cypress" },
    { value: "Dublin", text: "Dublin" },
    { value: "Covina", text: "Covina" },
    { value: "Azusa", text: "Azusa" },
    { value: "Palm Springs", text: "Palm Springs" },
    { value: "San Luis Obispo", text: "San Luis Obispo" },
    { value: "Ceres", text: "Ceres" },
    { value: "San Jacinto", text: "San Jacinto" },
    { value: "Lincoln", text: "Lincoln" },
    { value: "Newark", text: "Newark" },
    { value: "Lompoc", text: "Lompoc" },
    { value: "El Centro", text: "El Centro" },
    { value: "Danville", text: "Danville" },
    { value: "Bell Gardens", text: "Bell Gardens" },
    { value: "Coachella", text: "Coachella" },
    { value: "Rancho Palos Verdes", text: "Rancho Palos Verdes" },
    { value: "San Bruno", text: "San Bruno" },
    { value: "Rohnert Park", text: "Rohnert Park" },
    { value: "Brea", text: "Brea" },
    { value: "La Puente", text: "La Puente" },
    { value: "Campbell", text: "Campbell" },
    { value: "San Gabriel", text: "San Gabriel" },
    { value: "Beaumont", text: "Beaumont" },
    { value: "Morgan Hill", text: "Morgan Hill" },
    { value: "Culver City", text: "Culver City" },
    { value: "Calexico", text: "Calexico" },
    { value: "Stanton", text: "Stanton" },
    { value: "La Quinta", text: "La Quinta" },
    { value: "Pacifica", text: "Pacifica" },
    { value: "Montclair", text: "Montclair" },
    { value: "Oakley", text: "Oakley" },
    { value: "Monrovia", text: "Monrovia" },
    { value: "Los Banos", text: "Los Banos" },
    { value: "Martinez", text: "Martinez" },
  ],
  Illinois: [
    { value: "Chicago", text: "Chicago" },
    { value: "Aurora", text: "Aurora" },
    { value: "Rockford", text: "Rockford" },
    { value: "Joliet", text: "Joliet" },
    { value: "Naperville", text: "Naperville" },
    { value: "Springfield", text: "Springfield" },
    { value: "Peoria", text: "Peoria" },
    { value: "Elgin", text: "Elgin" },
    { value: "Waukegan", text: "Waukegan" },
    { value: "Cicero", text: "Cicero" },
    { value: "Champaign", text: "Champaign" },
    { value: "Bloomington", text: "Bloomington" },
    { value: "Arlington Heights", text: "Arlington Heights" },
    { value: "Evanston", text: "Evanston" },
    { value: "Decatur", text: "Decatur" },
    { value: "Schaumburg", text: "Schaumburg" },
    { value: "Bolingbrook", text: "Bolingbrook" },
    { value: "Palatine", text: "Palatine" },
    { value: "Skokie", text: "Skokie" },
    { value: "Des Plaines", text: "Des Plaines" },
    { value: "Orland Park", text: "Orland Park" },
    { value: "Tinley Park", text: "Tinley Park" },
    { value: "Oak Lawn", text: "Oak Lawn" },
    { value: "Berwyn", text: "Berwyn" },
    { value: "Mount Prospect", text: "Mount Prospect" },
    { value: "Normal", text: "Normal" },
    { value: "Wheaton", text: "Wheaton" },
    { value: "Hoffman Estates", text: "Hoffman Estates" },
    { value: "Oak Park", text: "Oak Park" },
    { value: "Downers Grove", text: "Downers Grove" },
    { value: "Elmhurst", text: "Elmhurst" },
    { value: "Glenview", text: "Glenview" },
    { value: "DeKalb", text: "DeKalb" },
    { value: "Lombard", text: "Lombard" },
    { value: "Belleville", text: "Belleville" },
    { value: "Moline", text: "Moline" },
    { value: "Buffalo Grove", text: "Buffalo Grove" },
    { value: "Bartlett", text: "Bartlett" },
    { value: "Urbana", text: "Urbana" },
    { value: "Quincy", text: "Quincy" },
    { value: "Crystal Lake", text: "Crystal Lake" },
    { value: "Plainfield", text: "Plainfield" },
    { value: "Streamwood", text: "Streamwood" },
    { value: "Carol Stream", text: "Carol Stream" },
    { value: "Romeoville", text: "Romeoville" },
    { value: "Rock Island", text: "Rock Island" },
    { value: "Hanover Park", text: "Hanover Park" },
    { value: "Carpentersville", text: "Carpentersville" },
    { value: "Wheeling", text: "Wheeling" },
    { value: "Park Ridge", text: "Park Ridge" },
    { value: "Addison", text: "Addison" },
    { value: "Calumet City", text: "Calumet City" },
  ],
  Texas: [
    { value: "Houston", text: "Houston" },
    { value: "San Antonio", text: "San Antonio" },
    { value: "Dallas", text: "Dallas" },
    { value: "Austin", text: "Austin" },
    { value: "Fort Worth", text: "Fort Worth" },
    { value: "El Paso", text: "El Paso" },
    { value: "Arlington", text: "Arlington" },
    { value: "Corpus Christi", text: "Corpus Christi" },
    { value: "Plano", text: "Plano" },
    { value: "Laredo", text: "Laredo" },
    { value: "Lubbock", text: "Lubbock" },
    { value: "Garland", text: "Garland" },
    { value: "Irving", text: "Irving" },
    { value: "Amarillo", text: "Amarillo" },
    { value: "Grand Prairie", text: "Grand Prairie" },
    { value: "Brownsville", text: "Brownsville" },
    { value: "Pasadena", text: "Pasadena" },
    { value: "McKinney", text: "McKinney" },
    { value: "Mesquite", text: "Mesquite" },
    { value: "McAllen", text: "McAllen" },
    { value: "Killeen", text: "Killeen" },
    { value: "Frisco", text: "Frisco" },
    { value: "Waco", text: "Waco" },
    { value: "Carrollton", text: "Carrollton" },
    { value: "Denton", text: "Denton" },
    { value: "Midland", text: "Midland" },
    { value: "Abilene", text: "Abilene" },
    { value: "Beaumont", text: "Beaumont" },
    { value: "Round Rock", text: "Round Rock" },
    { value: "Odessa", text: "Odessa" },
    { value: "Wichita Falls", text: "Wichita Falls" },
    { value: "Richardson", text: "Richardson" },
    { value: "Lewisville", text: "Lewisville" },
    { value: "Tyler", text: "Tyler" },
    { value: "College Station", text: "College Station" },
    { value: "Pearland", text: "Pearland" },
    { value: "San Angelo", text: "San Angelo" },
    { value: "Allen", text: "Allen" },
    { value: "League City", text: "League City" },
    { value: "Sugar Land", text: "Sugar Land" },
    { value: "Longview", text: "Longview" },
    { value: "Edinburg", text: "Edinburg" },
    { value: "Mission", text: "Mission" },
    { value: "Bryan", text: "Bryan" },
    { value: "Baytown", text: "Baytown" },
    { value: "Pharr", text: "Pharr" },
    { value: "Temple", text: "Temple" },
    { value: "Missouri City", text: "Missouri City" },
    { value: "Flower Mound", text: "Flower Mound" },
    { value: "Harlingen", text: "Harlingen" },
    { value: "North Richland Hills", text: "North Richland Hills" },
    { value: "Victoria", text: "Victoria" },
    { value: "Conroe", text: "Conroe" },
    { value: "New Braunfels", text: "New Braunfels" },
    { value: "Mansfield", text: "Mansfield" },
    { value: "Cedar Park", text: "Cedar Park" },
    { value: "Rowlett", text: "Rowlett" },
    { value: "Port Arthur", text: "Port Arthur" },
    { value: "Euless", text: "Euless" },
    { value: "Georgetown", text: "Georgetown" },
    { value: "Pflugerville", text: "Pflugerville" },
    { value: "DeSoto", text: "DeSoto" },
    { value: "San Marcos", text: "San Marcos" },
    { value: "Grapevine", text: "Grapevine" },
    { value: "Bedford", text: "Bedford" },
    { value: "Galveston", text: "Galveston" },
    { value: "Cedar Hill", text: "Cedar Hill" },
    { value: "Texas City", text: "Texas City" },
    { value: "Wylie", text: "Wylie" },
    { value: "Haltom City", text: "Haltom City" },
    { value: "Keller", text: "Keller" },
    { value: "Coppell", text: "Coppell" },
    { value: "Rockwall", text: "Rockwall" },
    { value: "Huntsville", text: "Huntsville" },
    { value: "Duncanville", text: "Duncanville" },
    { value: "Sherman", text: "Sherman" },
    { value: "The Colony", text: "The Colony" },
    { value: "Burleson", text: "Burleson" },
    { value: "Hurst", text: "Hurst" },
    { value: "Lancaster", text: "Lancaster" },
    { value: "Texarkana", text: "Texarkana" },
    { value: "Friendswood", text: "Friendswood" },
    { value: "Weslaco", text: "Weslaco" },
  ],
  Pennsylvania: [
    { value: "Philadelphia", text: "Philadelphia" },
    { value: "Pittsburgh", text: "Pittsburgh" },
    { value: "Allentown", text: "Allentown" },
    { value: "Erie", text: "Erie" },
    { value: "Reading", text: "Reading" },
    { value: "Scranton", text: "Scranton" },
    { value: "Bethlehem", text: "Bethlehem" },
    { value: "Lancaster", text: "Lancaster" },
    { value: "Harrisburg", text: "Harrisburg" },
    { value: "Altoona", text: "Altoona" },
    { value: "York", text: "York" },
    { value: "State College", text: "State College" },
    { value: "Wilkes-Barre", text: "Wilkes-Barre" },
  ],
  Arizona: [
    { value: "Phoenix", text: "Phoenix" },
    { value: "Tucson", text: "Tucson" },
    { value: "Mesa", text: "Mesa" },
    { value: "Chandler", text: "Chandler" },
    { value: "Glendale", text: "Glendale" },
    { value: "Scottsdale", text: "Scottsdale" },
    { value: "Gilbert", text: "Gilbert" },
    { value: "Tempe", text: "Tempe" },
    { value: "Peoria", text: "Peoria" },
    { value: "Surprise", text: "Surprise" },
    { value: "Yuma", text: "Yuma" },
    { value: "Avondale", text: "Avondale" },
    { value: "Goodyear", text: "Goodyear" },
    { value: "Flagstaff", text: "Flagstaff" },
    { value: "Buckeye", text: "Buckeye" },
    { value: "Lake Havasu City", text: "Lake Havasu City" },
    { value: "Casa Grande", text: "Casa Grande" },
    { value: "Sierra Vista", text: "Sierra Vista" },
    { value: "Maricopa", text: "Maricopa" },
    { value: "Oro Valley", text: "Oro Valley" },
    { value: "Prescott", text: "Prescott" },
    { value: "Bullhead City", text: "Bullhead City" },
    { value: "Prescott Valley", text: "Prescott Valley" },
    { value: "Marana", text: "Marana" },
    { value: "Apache Junction", text: "Apache Junction" },
  ],
  Florida: [
    { value: "Jacksonville", text: "Jacksonville" },
    { value: "Miami", text: "Miami" },
    { value: "Tampa", text: "Tampa" },
    { value: "Orlando", text: "Orlando" },
    { value: "St. Petersburg", text: "St. Petersburg" },
    { value: "Hialeah", text: "Hialeah" },
    { value: "Tallahassee", text: "Tallahassee" },
    { value: "Fort Lauderdale", text: "Fort Lauderdale" },
    { value: "Port St. Lucie", text: "Port St. Lucie" },
    { value: "Cape Coral", text: "Cape Coral" },
    { value: "Pembroke Pines", text: "Pembroke Pines" },
    { value: "Hollywood", text: "Hollywood" },
    { value: "Miramar", text: "Miramar" },
    { value: "Gainesville", text: "Gainesville" },
    { value: "Coral Springs", text: "Coral Springs" },
    { value: "Miami Gardens", text: "Miami Gardens" },
    { value: "Clearwater", text: "Clearwater" },
    { value: "Palm Bay", text: "Palm Bay" },
    { value: "Pompano Beach", text: "Pompano Beach" },
    { value: "West Palm Beach", text: "West Palm Beach" },
    { value: "Lakeland", text: "Lakeland" },
    { value: "Davie", text: "Davie" },
    { value: "Miami Beach", text: "Miami Beach" },
    { value: "Sunrise", text: "Sunrise" },
    { value: "Plantation", text: "Plantation" },
    { value: "Boca Raton", text: "Boca Raton" },
    { value: "Deltona", text: "Deltona" },
    { value: "Largo", text: "Largo" },
    { value: "Deerfield Beach", text: "Deerfield Beach" },
    { value: "Palm Coast", text: "Palm Coast" },
    { value: "Melbourne", text: "Melbourne" },
    { value: "Boynton Beach", text: "Boynton Beach" },
    { value: "Lauderhill", text: "Lauderhill" },
    { value: "Weston", text: "Weston" },
    { value: "Fort Myers", text: "Fort Myers" },
    { value: "Kissimmee", text: "Kissimmee" },
    { value: "Homestead", text: "Homestead" },
    { value: "Tamarac", text: "Tamarac" },
    { value: "Delray Beach", text: "Delray Beach" },
    { value: "Daytona Beach", text: "Daytona Beach" },
    { value: "North Miami", text: "North Miami" },
    { value: "Wellington", text: "Wellington" },
    { value: "North Port", text: "North Port" },
    { value: "Jupiter", text: "Jupiter" },
    { value: "Ocala", text: "Ocala" },
    { value: "Port Orange", text: "Port Orange" },
    { value: "Margate", text: "Margate" },
    { value: "Coconut Creek", text: "Coconut Creek" },
    { value: "Sanford", text: "Sanford" },
    { value: "Sarasota", text: "Sarasota" },
    { value: "Pensacola", text: "Pensacola" },
    { value: "Bradenton", text: "Bradenton" },
    { value: "Palm Beach Gardens", text: "Palm Beach Gardens" },
    { value: "Pinellas Park", text: "Pinellas Park" },
    { value: "Coral Gables", text: "Coral Gables" },
    { value: "Doral", text: "Doral" },
    { value: "Bonita Springs", text: "Bonita Springs" },
    { value: "Apopka", text: "Apopka" },
    { value: "Titusville", text: "Titusville" },
    { value: "North Miami Beach", text: "North Miami Beach" },
    { value: "Oakland Park", text: "Oakland Park" },
    { value: "Fort Pierce", text: "Fort Pierce" },
    { value: "North Lauderdale", text: "North Lauderdale" },
    { value: "Cutler Bay", text: "Cutler Bay" },
    { value: "Altamonte Springs", text: "Altamonte Springs" },
    { value: "St. Cloud", text: "St. Cloud" },
    { value: "Greenacres", text: "Greenacres" },
    { value: "Ormond Beach", text: "Ormond Beach" },
    { value: "Ocoee", text: "Ocoee" },
    { value: "Hallandale Beach", text: "Hallandale Beach" },
    { value: "Winter Garden", text: "Winter Garden" },
    { value: "Aventura", text: "Aventura" },
  ],
  Indiana: [
    { value: "Indianapolis", text: "Indianapolis" },
    { value: "Fort Wayne", text: "Fort Wayne" },
    { value: "Evansville", text: "Evansville" },
    { value: "South Bend", text: "South Bend" },
    { value: "Carmel", text: "Carmel" },
    { value: "Bloomington", text: "Bloomington" },
    { value: "Fishers", text: "Fishers" },
    { value: "Hammond", text: "Hammond" },
    { value: "Gary", text: "Gary" },
    { value: "Muncie", text: "Muncie" },
    { value: "Lafayette", text: "Lafayette" },
    { value: "Terre Haute", text: "Terre Haute" },
    { value: "Kokomo", text: "Kokomo" },
    { value: "Anderson", text: "Anderson" },
    { value: "Noblesville", text: "Noblesville" },
    { value: "Greenwood", text: "Greenwood" },
    { value: "Elkhart", text: "Elkhart" },
    { value: "Mishawaka", text: "Mishawaka" },
    { value: "Lawrence", text: "Lawrence" },
    { value: "Jeffersonville", text: "Jeffersonville" },
    { value: "Columbus", text: "Columbus" },
    { value: "Portage", text: "Portage" },
  ],
  Ohio: [
    { value: "Columbus", text: "Columbus" },
    { value: "Cleveland", text: "Cleveland" },
    { value: "Cincinnati", text: "Cincinnati" },
    { value: "Toledo", text: "Toledo" },
    { value: "Akron", text: "Akron" },
    { value: "Dayton", text: "Dayton" },
    { value: "Parma", text: "Parma" },
    { value: "Canton", text: "Canton" },
    { value: "Youngstown", text: "Youngstown" },
    { value: "Lorain", text: "Lorain" },
    { value: "Hamilton", text: "Hamilton" },
    { value: "Springfield", text: "Springfield" },
    { value: "Kettering", text: "Kettering" },
    { value: "Elyria", text: "Elyria" },
    { value: "Lakewood", text: "Lakewood" },
    { value: "Cuyahoga Falls", text: "Cuyahoga Falls" },
    { value: "Middletown", text: "Middletown" },
    { value: "Euclid", text: "Euclid" },
    { value: "Newark", text: "Newark" },
    { value: "Mansfield", text: "Mansfield" },
    { value: "Mentor", text: "Mentor" },
    { value: "Beavercreek", text: "Beavercreek" },
    { value: "Cleveland Heights", text: "Cleveland Heights" },
    { value: "Strongsville", text: "Strongsville" },
    { value: "Dublin", text: "Dublin" },
    { value: "Fairfield", text: "Fairfield" },
    { value: "Findlay", text: "Findlay" },
    { value: "Warren", text: "Warren" },
    { value: "Lancaster", text: "Lancaster" },
    { value: "Lima", text: "Lima" },
    { value: "Huber Heights", text: "Huber Heights" },
    { value: "Westerville", text: "Westerville" },
    { value: "Marion", text: "Marion" },
    { value: "Grove City", text: "Grove City" },
  ],
  "North Carolina": [
    { value: "Charlotte", text: "Charlotte" },
    { value: "Raleigh", text: "Raleigh" },
    { value: "Greensboro", text: "Greensboro" },
    { value: "Durham", text: "Durham" },
    { value: "Winston-Salem", text: "Winston-Salem" },
    { value: "Fayetteville", text: "Fayetteville" },
    { value: "Cary", text: "Cary" },
    { value: "Wilmington", text: "Wilmington" },
    { value: "High Point", text: "High Point" },
    { value: "Greenville", text: "Greenville" },
    { value: "Asheville", text: "Asheville" },
    { value: "Concord", text: "Concord" },
    { value: "Gastonia", text: "Gastonia" },
    { value: "Jacksonville", text: "Jacksonville" },
    { value: "Chapel Hill", text: "Chapel Hill" },
    { value: "Rocky Mount", text: "Rocky Mount" },
    { value: "Burlington", text: "Burlington" },
    { value: "Wilson", text: "Wilson" },
    { value: "Huntersville", text: "Huntersville" },
    { value: "Kannapolis", text: "Kannapolis" },
    { value: "Apex", text: "Apex" },
    { value: "Hickory", text: "Hickory" },
    { value: "Goldsboro", text: "Goldsboro" },
  ],
  Michigan: [
    { value: "Detroit", text: "Detroit" },
    { value: "Grand Rapids", text: "Grand Rapids" },
    { value: "Warren", text: "Warren" },
    { value: "Sterling Heights", text: "Sterling Heights" },
    { value: "Ann Arbor", text: "Ann Arbor" },
    { value: "Lansing", text: "Lansing" },
    { value: "Flint", text: "Flint" },
    { value: "Dearborn", text: "Dearborn" },
    { value: "Livonia", text: "Livonia" },
    { value: "Westland", text: "Westland" },
    { value: "Troy", text: "Troy" },
    { value: "Farmington Hills", text: "Farmington Hills" },
    { value: "Kalamazoo", text: "Kalamazoo" },
    { value: "Wyoming", text: "Wyoming" },
    { value: "Southfield", text: "Southfield" },
    { value: "Rochester Hills", text: "Rochester Hills" },
    { value: "Taylor", text: "Taylor" },
    { value: "Pontiac", text: "Pontiac" },
    { value: "St. Clair Shores", text: "St. Clair Shores" },
    { value: "Royal Oak", text: "Royal Oak" },
    { value: "Novi", text: "Novi" },
    { value: "Dearborn Heights", text: "Dearborn Heights" },
    { value: "Battle Creek", text: "Battle Creek" },
    { value: "Saginaw", text: "Saginaw" },
    { value: "Kentwood", text: "Kentwood" },
    { value: "East Lansing", text: "East Lansing" },
    { value: "Roseville", text: "Roseville" },
    { value: "Portage", text: "Portage" },
    { value: "Midland", text: "Midland" },
    { value: "Lincoln Park", text: "Lincoln Park" },
    { value: "Muskegon", text: "Muskegon" },
  ],
  Tennessee: [
    { value: "Memphis", text: "Memphis" },
    { value: "Nashville-Davidson", text: "Nashville-Davidson" },
    { value: "Knoxville", text: "Knoxville" },
    { value: "Chattanooga", text: "Chattanooga" },
    { value: "Clarksville", text: "Clarksville" },
    { value: "Murfreesboro", text: "Murfreesboro" },
    { value: "Jackson", text: "Jackson" },
    { value: "Franklin", text: "Franklin" },
    { value: "Johnson City", text: "Johnson City" },
    { value: "Bartlett", text: "Bartlett" },
    { value: "Hendersonville", text: "Hendersonville" },
    { value: "Kingsport", text: "Kingsport" },
    { value: "Collierville", text: "Collierville" },
    { value: "Cleveland", text: "Cleveland" },
    { value: "Smyrna", text: "Smyrna" },
    { value: "Germantown", text: "Germantown" },
    { value: "Brentwood", text: "Brentwood" },
  ],
  Massachusetts: [
    { value: "Boston", text: "Boston" },
    { value: "Worcester", text: "Worcester" },
    { value: "Springfield", text: "Springfield" },
    { value: "Lowell", text: "Lowell" },
    { value: "Cambridge", text: "Cambridge" },
    { value: "New Bedford", text: "New Bedford" },
    { value: "Brockton", text: "Brockton" },
    { value: "Quincy", text: "Quincy" },
    { value: "Lynn", text: "Lynn" },
    { value: "Fall River", text: "Fall River" },
    { value: "Newton", text: "Newton" },
    { value: "Lawrence", text: "Lawrence" },
    { value: "Somerville", text: "Somerville" },
    { value: "Waltham", text: "Waltham" },
    { value: "Haverhill", text: "Haverhill" },
    { value: "Malden", text: "Malden" },
    { value: "Medford", text: "Medford" },
    { value: "Taunton", text: "Taunton" },
    { value: "Chicopee", text: "Chicopee" },
    { value: "Weymouth Town", text: "Weymouth Town" },
    { value: "Revere", text: "Revere" },
    { value: "Peabody", text: "Peabody" },
    { value: "Methuen", text: "Methuen" },
    { value: "Barnstable Town", text: "Barnstable Town" },
    { value: "Pittsfield", text: "Pittsfield" },
    { value: "Attleboro", text: "Attleboro" },
    { value: "Everett", text: "Everett" },
    { value: "Salem", text: "Salem" },
    { value: "Westfield", text: "Westfield" },
    { value: "Leominster", text: "Leominster" },
    { value: "Fitchburg", text: "Fitchburg" },
    { value: "Beverly", text: "Beverly" },
    { value: "Holyoke", text: "Holyoke" },
    { value: "Marlborough", text: "Marlborough" },
    { value: "Woburn", text: "Woburn" },
    { value: "Chelsea", text: "Chelsea" },
  ],
  Washington: [
    { value: "Seattle", text: "Seattle" },
    { value: "Spokane", text: "Spokane" },
    { value: "Tacoma", text: "Tacoma" },
    { value: "Vancouver", text: "Vancouver" },
    { value: "Bellevue", text: "Bellevue" },
    { value: "Kent", text: "Kent" },
    { value: "Everett", text: "Everett" },
    { value: "Renton", text: "Renton" },
    { value: "Yakima", text: "Yakima" },
    { value: "Federal Way", text: "Federal Way" },
    { value: "Spokane Valley", text: "Spokane Valley" },
    { value: "Bellingham", text: "Bellingham" },
    { value: "Kennewick", text: "Kennewick" },
    { value: "Auburn", text: "Auburn" },
    { value: "Pasco", text: "Pasco" },
    { value: "Marysville", text: "Marysville" },
    { value: "Lakewood", text: "Lakewood" },
    { value: "Redmond", text: "Redmond" },
    { value: "Shoreline", text: "Shoreline" },
    { value: "Richland", text: "Richland" },
    { value: "Kirkland", text: "Kirkland" },
    { value: "Burien", text: "Burien" },
    { value: "Sammamish", text: "Sammamish" },
    { value: "Olympia", text: "Olympia" },
    { value: "Lacey", text: "Lacey" },
    { value: "Edmonds", text: "Edmonds" },
    { value: "Bremerton", text: "Bremerton" },
    { value: "Puyallup", text: "Puyallup" },
  ],
  Colorado: [
    { value: "Denver", text: "Denver" },
    { value: "Colorado Springs", text: "Colorado Springs" },
    { value: "Aurora", text: "Aurora" },
    { value: "Fort Collins", text: "Fort Collins" },
    { value: "Lakewood", text: "Lakewood" },
    { value: "Thornton", text: "Thornton" },
    { value: "Arvada", text: "Arvada" },
    { value: "Westminster", text: "Westminster" },
    { value: "Pueblo", text: "Pueblo" },
    { value: "Centennial", text: "Centennial" },
    { value: "Boulder", text: "Boulder" },
    { value: "Greeley", text: "Greeley" },
    { value: "Longmont", text: "Longmont" },
    { value: "Loveland", text: "Loveland" },
    { value: "Grand Junction", text: "Grand Junction" },
    { value: "Broomfield", text: "Broomfield" },
    { value: "Castle Rock", text: "Castle Rock" },
    { value: "Commerce City", text: "Commerce City" },
    { value: "Parker", text: "Parker" },
    { value: "Littleton", text: "Littleton" },
    { value: "Northglenn", text: "Northglenn" },
  ],
  "District of Columbia": [{ value: "Washington", text: "Washington" }],
  Maryland: [
    { value: "Baltimore", text: "Baltimore" },
    { value: "Frederick", text: "Frederick" },
    { value: "Rockville", text: "Rockville" },
    { value: "Gaithersburg", text: "Gaithersburg" },
    { value: "Bowie", text: "Bowie" },
    { value: "Hagerstown", text: "Hagerstown" },
    { value: "Annapolis", text: "Annapolis" },
  ],
  Kentucky: [
    {
      value: "Louisville/Jefferson County",
      text: "Louisville/Jefferson County",
    },
    { value: "Lexington-Fayette", text: "Lexington-Fayette" },
    { value: "Bowling Green", text: "Bowling Green" },
    { value: "Owensboro", text: "Owensboro" },
    { value: "Covington", text: "Covington" },
  ],
  Oregon: [
    { value: "Portland", text: "Portland" },
    { value: "Eugene", text: "Eugene" },
    { value: "Salem", text: "Salem" },
    { value: "Gresham", text: "Gresham" },
    { value: "Hillsboro", text: "Hillsboro" },
    { value: "Beaverton", text: "Beaverton" },
    { value: "Bend", text: "Bend" },
    { value: "Medford", text: "Medford" },
    { value: "Springfield", text: "Springfield" },
    { value: "Corvallis", text: "Corvallis" },
    { value: "Albany", text: "Albany" },
    { value: "Tigard", text: "Tigard" },
    { value: "Lake Oswego", text: "Lake Oswego" },
    { value: "Keizer", text: "Keizer" },
  ],
  Oklahoma: [
    { value: "Oklahoma City", text: "Oklahoma City" },
    { value: "Tulsa", text: "Tulsa" },
    { value: "Norman", text: "Norman" },
    { value: "Broken Arrow", text: "Broken Arrow" },
    { value: "Lawton", text: "Lawton" },
    { value: "Edmond", text: "Edmond" },
    { value: "Moore", text: "Moore" },
    { value: "Midwest City", text: "Midwest City" },
    { value: "Enid", text: "Enid" },
    { value: "Stillwater", text: "Stillwater" },
    { value: "Muskogee", text: "Muskogee" },
  ],
  Wisconsin: [
    { value: "Milwaukee", text: "Milwaukee" },
    { value: "Madison", text: "Madison" },
    { value: "Green Bay", text: "Green Bay" },
    { value: "Kenosha", text: "Kenosha" },
    { value: "Racine", text: "Racine" },
    { value: "Appleton", text: "Appleton" },
    { value: "Waukesha", text: "Waukesha" },
    { value: "Eau Claire", text: "Eau Claire" },
    { value: "Oshkosh", text: "Oshkosh" },
    { value: "Janesville", text: "Janesville" },
    { value: "West Allis", text: "West Allis" },
    { value: "La Crosse", text: "La Crosse" },
    { value: "Sheboygan", text: "Sheboygan" },
    { value: "Wauwatosa", text: "Wauwatosa" },
    { value: "Fond du Lac", text: "Fond du Lac" },
    { value: "New Berlin", text: "New Berlin" },
    { value: "Wausau", text: "Wausau" },
    { value: "Brookfield", text: "Brookfield" },
    { value: "Greenfield", text: "Greenfield" },
    { value: "Beloit", text: "Beloit" },
  ],
  Nevada: [
    { value: "Las Vegas", text: "Las Vegas" },
    { value: "Henderson", text: "Henderson" },
    { value: "Reno", text: "Reno" },
    { value: "North Las Vegas", text: "North Las Vegas" },
    { value: "Sparks", text: "Sparks" },
    { value: "Carson City", text: "Carson City" },
  ],
  "New Mexico": [
    { value: "Albuquerque", text: "Albuquerque" },
    { value: "Las Cruces", text: "Las Cruces" },
    { value: "Rio Rancho", text: "Rio Rancho" },
    { value: "Santa Fe", text: "Santa Fe" },
    { value: "Roswell", text: "Roswell" },
    { value: "Farmington", text: "Farmington" },
    { value: "Clovis", text: "Clovis" },
  ],
  Missouri: [
    { value: "Kansas City", text: "Kansas City" },
    { value: "St. Louis", text: "St. Louis" },
    { value: "Springfield", text: "Springfield" },
    { value: "Independence", text: "Independence" },
    { value: "Columbia", text: "Columbia" },
    { value: "Lee's Summit", text: "Lee's Summit" },
    { value: "O'Fallon", text: "O'Fallon" },
    { value: "St. Joseph", text: "St. Joseph" },
    { value: "St. Charles", text: "St. Charles" },
    { value: "St. Peters", text: "St. Peters" },
    { value: "Blue Springs", text: "Blue Springs" },
    { value: "Florissant", text: "Florissant" },
    { value: "Joplin", text: "Joplin" },
    { value: "Chesterfield", text: "Chesterfield" },
    { value: "Jefferson City", text: "Jefferson City" },
    { value: "Cape Girardeau", text: "Cape Girardeau" },
  ],
  Virginia: [
    { value: "Virginia Beach", text: "Virginia Beach" },
    { value: "Norfolk", text: "Norfolk" },
    { value: "Chesapeake", text: "Chesapeake" },
    { value: "Richmond", text: "Richmond" },
    { value: "Newport News", text: "Newport News" },
    { value: "Alexandria", text: "Alexandria" },
    { value: "Hampton", text: "Hampton" },
    { value: "Roanoke", text: "Roanoke" },
    { value: "Portsmouth", text: "Portsmouth" },
    { value: "Suffolk", text: "Suffolk" },
    { value: "Lynchburg", text: "Lynchburg" },
    { value: "Harrisonburg", text: "Harrisonburg" },
    { value: "Leesburg", text: "Leesburg" },
    { value: "Charlottesville", text: "Charlottesville" },
    { value: "Danville", text: "Danville" },
    { value: "Blacksburg", text: "Blacksburg" },
    { value: "Manassas", text: "Manassas" },
  ],
  Georgia: [
    { value: "Atlanta", text: "Atlanta" },
    { value: "Columbus", text: "Columbus" },
    { value: "Augusta-Richmond County", text: "Augusta-Richmond County" },
    { value: "Savannah", text: "Savannah" },
    { value: "Athens-Clarke County", text: "Athens-Clarke County" },
    { value: "Sandy Springs", text: "Sandy Springs" },
    { value: "Roswell", text: "Roswell" },
    { value: "Macon", text: "Macon" },
    { value: "Johns Creek", text: "Johns Creek" },
    { value: "Albany", text: "Albany" },
    { value: "Warner Robins", text: "Warner Robins" },
    { value: "Alpharetta", text: "Alpharetta" },
    { value: "Marietta", text: "Marietta" },
    { value: "Valdosta", text: "Valdosta" },
    { value: "Smyrna", text: "Smyrna" },
    { value: "Dunwoody", text: "Dunwoody" },
  ],
  Nebraska: [
    { value: "Omaha", text: "Omaha" },
    { value: "Lincoln", text: "Lincoln" },
    { value: "Bellevue", text: "Bellevue" },
    { value: "Grand Island", text: "Grand Island" },
  ],
  Minnesota: [
    { value: "Minneapolis", text: "Minneapolis" },
    { value: "St. Paul", text: "St. Paul" },
    { value: "Rochester", text: "Rochester" },
    { value: "Duluth", text: "Duluth" },
    { value: "Bloomington", text: "Bloomington" },
    { value: "Brooklyn Park", text: "Brooklyn Park" },
    { value: "Plymouth", text: "Plymouth" },
    { value: "St. Cloud", text: "St. Cloud" },
    { value: "Eagan", text: "Eagan" },
    { value: "Woodbury", text: "Woodbury" },
    { value: "Maple Grove", text: "Maple Grove" },
    { value: "Eden Prairie", text: "Eden Prairie" },
    { value: "Coon Rapids", text: "Coon Rapids" },
    { value: "Burnsville", text: "Burnsville" },
    { value: "Blaine", text: "Blaine" },
    { value: "Lakeville", text: "Lakeville" },
    { value: "Minnetonka", text: "Minnetonka" },
    { value: "Apple Valley", text: "Apple Valley" },
    { value: "Edina", text: "Edina" },
    { value: "St. Louis Park", text: "St. Louis Park" },
    { value: "Mankato", text: "Mankato" },
    { value: "Maplewood", text: "Maplewood" },
    { value: "Moorhead", text: "Moorhead" },
    { value: "Shakopee", text: "Shakopee" },
  ],
  Kansas: [
    { value: "Wichita", text: "Wichita" },
    { value: "Overland Park", text: "Overland Park" },
    { value: "Kansas City", text: "Kansas City" },
    { value: "Olathe", text: "Olathe" },
    { value: "Topeka", text: "Topeka" },
    { value: "Lawrence", text: "Lawrence" },
    { value: "Shawnee", text: "Shawnee" },
    { value: "Manhattan", text: "Manhattan" },
    { value: "Lenexa", text: "Lenexa" },
    { value: "Salina", text: "Salina" },
    { value: "Hutchinson", text: "Hutchinson" },
  ],
  Louisiana: [
    { value: "New Orleans", text: "New Orleans" },
    { value: "Baton Rouge", text: "Baton Rouge" },
    { value: "Shreveport", text: "Shreveport" },
    { value: "Lafayette", text: "Lafayette" },
    { value: "Lake Charles", text: "Lake Charles" },
    { value: "Kenner", text: "Kenner" },
    { value: "Bossier City", text: "Bossier City" },
    { value: "Monroe", text: "Monroe" },
    { value: "Alexandria", text: "Alexandria" },
  ],
  Hawaii: [{ value: "Honolulu", text: "Honolulu" }],
  Alaska: [{ value: "Anchorage", text: "Anchorage" }],
  "New Jersey": [
    { value: "Newark", text: "Newark" },
    { value: "Jersey City", text: "Jersey City" },
    { value: "Paterson", text: "Paterson" },
    { value: "Elizabeth", text: "Elizabeth" },
    { value: "Clifton", text: "Clifton" },
    { value: "Trenton", text: "Trenton" },
    { value: "Camden", text: "Camden" },
    { value: "Passaic", text: "Passaic" },
    { value: "Union City", text: "Union City" },
    { value: "Bayonne", text: "Bayonne" },
    { value: "East Orange", text: "East Orange" },
    { value: "Vineland", text: "Vineland" },
    { value: "New Brunswick", text: "New Brunswick" },
    { value: "Hoboken", text: "Hoboken" },
    { value: "Perth Amboy", text: "Perth Amboy" },
    { value: "West New York", text: "West New York" },
    { value: "Plainfield", text: "Plainfield" },
    { value: "Hackensack", text: "Hackensack" },
    { value: "Sayreville", text: "Sayreville" },
    { value: "Kearny", text: "Kearny" },
    { value: "Linden", text: "Linden" },
    { value: "Atlantic City", text: "Atlantic City" },
  ],
  Idaho: [
    { value: "Boise City", text: "Boise City" },
    { value: "Nampa", text: "Nampa" },
    { value: "Meridian", text: "Meridian" },
    { value: "Idaho Falls", text: "Idaho Falls" },
    { value: "Pocatello", text: "Pocatello" },
    { value: "Caldwell", text: "Caldwell" },
    { value: "Coeur d'Alene", text: "Coeur d'Alene" },
    { value: "Twin Falls", text: "Twin Falls" },
  ],
  Alabama: [
    { value: "Birmingham", text: "Birmingham" },
    { value: "Montgomery", text: "Montgomery" },
    { value: "Mobile", text: "Mobile" },
    { value: "Huntsville", text: "Huntsville" },
    { value: "Tuscaloosa", text: "Tuscaloosa" },
    { value: "Hoover", text: "Hoover" },
    { value: "Dothan", text: "Dothan" },
    { value: "Auburn", text: "Auburn" },
    { value: "Decatur", text: "Decatur" },
    { value: "Madison", text: "Madison" },
    { value: "Florence", text: "Florence" },
    { value: "Gadsden", text: "Gadsden" },
  ],
  Iowa: [
    { value: "Des Moines", text: "Des Moines" },
    { value: "Cedar Rapids", text: "Cedar Rapids" },
    { value: "Davenport", text: "Davenport" },
    { value: "Sioux City", text: "Sioux City" },
    { value: "Iowa City", text: "Iowa City" },
    { value: "Waterloo", text: "Waterloo" },
    { value: "Council Bluffs", text: "Council Bluffs" },
    { value: "Ames", text: "Ames" },
    { value: "West Des Moines", text: "West Des Moines" },
    { value: "Dubuque", text: "Dubuque" },
    { value: "Ankeny", text: "Ankeny" },
    { value: "Urbandale", text: "Urbandale" },
    { value: "Cedar Falls", text: "Cedar Falls" },
  ],
  Arkansas: [
    { value: "Little Rock", text: "Little Rock" },
    { value: "Fort Smith", text: "Fort Smith" },
    { value: "Fayetteville", text: "Fayetteville" },
    { value: "Springdale", text: "Springdale" },
    { value: "Jonesboro", text: "Jonesboro" },
    { value: "North Little Rock", text: "North Little Rock" },
    { value: "Conway", text: "Conway" },
    { value: "Rogers", text: "Rogers" },
    { value: "Pine Bluff", text: "Pine Bluff" },
    { value: "Bentonville", text: "Bentonville" },
  ],
  Utah: [
    { value: "Salt Lake City", text: "Salt Lake City" },
    { value: "West Valley City", text: "West Valley City" },
    { value: "Provo", text: "Provo" },
    { value: "West Jordan", text: "West Jordan" },
    { value: "Orem", text: "Orem" },
    { value: "Sandy", text: "Sandy" },
    { value: "Ogden", text: "Ogden" },
    { value: "St. George", text: "St. George" },
    { value: "Layton", text: "Layton" },
    { value: "Taylorsville", text: "Taylorsville" },
    { value: "South Jordan", text: "South Jordan" },
    { value: "Lehi", text: "Lehi" },
    { value: "Logan", text: "Logan" },
    { value: "Murray", text: "Murray" },
    { value: "Draper", text: "Draper" },
    { value: "Bountiful", text: "Bountiful" },
    { value: "Riverton", text: "Riverton" },
    { value: "Roy", text: "Roy" },
  ],
  "Rhode Island": [
    { value: "Providence", text: "Providence" },
    { value: "Warwick", text: "Warwick" },
    { value: "Cranston", text: "Cranston" },
    { value: "Pawtucket", text: "Pawtucket" },
    { value: "East Providence", text: "East Providence" },
    { value: "Woonsocket", text: "Woonsocket" },
  ],
  Mississippi: [
    { value: "Jackson", text: "Jackson" },
    { value: "Gulfport", text: "Gulfport" },
    { value: "Southaven", text: "Southaven" },
    { value: "Hattiesburg", text: "Hattiesburg" },
    { value: "Biloxi", text: "Biloxi" },
    { value: "Meridian", text: "Meridian" },
  ],
  "South Dakota": [
    { value: "Sioux Falls", text: "Sioux Falls" },
    { value: "Rapid City", text: "Rapid City" },
  ],
  Connecticut: [
    { value: "Bridgeport", text: "Bridgeport" },
    { value: "New Haven", text: "New Haven" },
    { value: "Stamford", text: "Stamford" },
    { value: "Hartford", text: "Hartford" },
    { value: "Waterbury", text: "Waterbury" },
    { value: "Norwalk", text: "Norwalk" },
    { value: "Danbury", text: "Danbury" },
    { value: "New Britain", text: "New Britain" },
    { value: "Meriden", text: "Meriden" },
    { value: "Bristol", text: "Bristol" },
    { value: "West Haven", text: "West Haven" },
    { value: "Milford", text: "Milford" },
    { value: "Middletown", text: "Middletown" },
    { value: "Norwich", text: "Norwich" },
    { value: "Shelton", text: "Shelton" },
  ],
  "South Carolina": [
    { value: "Columbia", text: "Columbia" },
    { value: "Charleston", text: "Charleston" },
    { value: "North Charleston", text: "North Charleston" },
    { value: "Mount Pleasant", text: "Mount Pleasant" },
    { value: "Rock Hill", text: "Rock Hill" },
    { value: "Greenville", text: "Greenville" },
    { value: "Summerville", text: "Summerville" },
    { value: "Sumter", text: "Sumter" },
    { value: "Goose Creek", text: "Goose Creek" },
    { value: "Hilton Head Island", text: "Hilton Head Island" },
    { value: "Florence", text: "Florence" },
    { value: "Spartanburg", text: "Spartanburg" },
  ],
  "New Hampshire": [
    { value: "Manchester", text: "Manchester" },
    { value: "Nashua", text: "Nashua" },
    { value: "Concord", text: "Concord" },
  ],
  "North Dakota": [
    { value: "Fargo", text: "Fargo" },
    { value: "Bismarck", text: "Bismarck" },
    { value: "Grand Forks", text: "Grand Forks" },
    { value: "Minot", text: "Minot" },
  ],
  Montana: [
    { value: "Billings", text: "Billings" },
    { value: "Missoula", text: "Missoula" },
    { value: "Great Falls", text: "Great Falls" },
    { value: "Bozeman", text: "Bozeman" },
  ],
  Delaware: [
    { value: "Wilmington", text: "Wilmington" },
    { value: "Dover", text: "Dover" },
  ],
  Maine: [{ value: "Portland", text: "Portland" }],
  Wyoming: [
    { value: "Cheyenne", text: "Cheyenne" },
    { value: "Casper", text: "Casper" },
  ],
  "West Virginia": [
    { value: "Charleston", text: "Charleston" },
    { value: "Huntington", text: "Huntington" },
  ],
  Vermont: [{ value: "Burlington", text: "Burlington" }],
};
