export const OFFSETS = [
  {
    fTimeZoneID: 101,
    fTimeZoneName: "Australian Central Standard Time",
    fTimeZoneAbbrev: "ACST",
    fOffset: 9.5,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 102,
    fTimeZoneName: "Australian Central Daylight Time",
    fTimeZoneAbbrev: "ACDT",
    fOffset: 10,
    fStandardTime: 0,
  },
  {
    fTimeZoneID: 201,
    fTimeZoneName: "ASEAN Common Time",
    fTimeZoneAbbrev: "ACT",
    fOffset: 8,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 301,
    fTimeZoneName: "Australian Eastern Standard Time",
    fTimeZoneAbbrev: "AEST",
    fOffset: 10,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 302,
    fTimeZoneName: "Australian Eastern Daylight Time",
    fTimeZoneAbbrev: "AEDT",
    fOffset: 11,
    fStandardTime: 0,
  },
  {
    fTimeZoneID: 401,
    fTimeZoneName: "Afghanistan Time",
    fTimeZoneAbbrev: "AFT",
    fOffset: 4.5,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 501,
    fTimeZoneName: "Alaska Standard Time",
    fTimeZoneAbbrev: "AKST",
    fOffset: -9,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 502,
    fTimeZoneName: "Alaska Daylight Time",
    fTimeZoneAbbrev: "AKDT",
    fOffset: -8,
    fStandardTime: 0,
  },
  {
    fTimeZoneID: 601,
    fTimeZoneName: "Armenia Time",
    fTimeZoneAbbrev: "AMT",
    fOffset: 4,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 701,
    fTimeZoneName: "Argentina Time",
    fTimeZoneAbbrev: "ART",
    fOffset: -3,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 801,
    fTimeZoneName: "Arabia Standard Time",
    fTimeZoneAbbrev: "AST",
    fOffset: 3,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 901,
    fTimeZoneName: "Arabian Standard Time (Abu Dhabi)",
    fTimeZoneAbbrev: "AST",
    fOffset: 4,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 1001,
    fTimeZoneName: "Arabic Standard Time (Baghdad)",
    fTimeZoneAbbrev: "AST",
    fOffset: 3,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 1101,
    fTimeZoneName: "Atlantic Standard Time",
    fTimeZoneAbbrev: "AST",
    fOffset: -4,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 1102,
    fTimeZoneName: "Atlantic Daylight Time",
    fTimeZoneAbbrev: "ADT",
    fOffset: -3,
    fStandardTime: 0,
  },
  {
    fTimeZoneID: 1201,
    fTimeZoneName: "Australian Western Standard Time",
    fTimeZoneAbbrev: "AWST",
    fOffset: 8,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 1301,
    fTimeZoneName: "Azores Standard Time",
    fTimeZoneAbbrev: "AZOT",
    fOffset: -1,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 1302,
    fTimeZoneName: "Azores Summer Time",
    fTimeZoneAbbrev: "AZOST",
    fOffset: 0,
    fStandardTime: 0,
  },
  {
    fTimeZoneID: 1401,
    fTimeZoneName: "Azerbaijan Time",
    fTimeZoneAbbrev: "AZT",
    fOffset: 4,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 1402,
    fTimeZoneName: "Azerbaijan Summer Time",
    fTimeZoneAbbrev: "AZST",
    fOffset: 5,
    fStandardTime: 0,
  },
  {
    fTimeZoneID: 1501,
    fTimeZoneName: "Brunei Time",
    fTimeZoneAbbrev: "BDT",
    fOffset: 8,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 1601,
    fTimeZoneName: "British Indian Ocean Time",
    fTimeZoneAbbrev: "BIOT",
    fOffset: 6,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 1701,
    fTimeZoneName: "Baker Island Time",
    fTimeZoneAbbrev: "BIT",
    fOffset: -12,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 1801,
    fTimeZoneName: "Paraguay Time",
    fTimeZoneAbbrev: "PYT",
    fOffset: -4,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 1802,
    fTimeZoneName: "Paraguay Summer Time",
    fTimeZoneAbbrev: "PYST",
    fOffset: -3,
    fStandardTime: 0,
  },
  {
    fTimeZoneID: 1901,
    fTimeZoneName: "Brasilia Time",
    fTimeZoneAbbrev: "BRT",
    fOffset: -3,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 1902,
    fTimeZoneName: "Brasilia Summer Time",
    fTimeZoneAbbrev: "BRST",
    fOffset: -2,
    fStandardTime: 0,
  },
  {
    fTimeZoneID: 2001,
    fTimeZoneName: "Bangladesh Standard Time",
    fTimeZoneAbbrev: "BST",
    fOffset: 6,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 2101,
    fTimeZoneName: "Bhutan Time",
    fTimeZoneAbbrev: "BTT",
    fOffset: 6,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 2201,
    fTimeZoneName: "Central Africa Time",
    fTimeZoneAbbrev: "CAT",
    fOffset: 2,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 2301,
    fTimeZoneName: "Cocos Islands Time",
    fTimeZoneAbbrev: "CCT",
    fOffset: 6.5,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 2401,
    fTimeZoneName: "Central European Time",
    fTimeZoneAbbrev: "CET",
    fOffset: 1,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 2402,
    fTimeZoneName: "Central European Summer Time",
    fTimeZoneAbbrev: "CEST",
    fOffset: 2,
    fStandardTime: 0,
  },
  {
    fTimeZoneID: 2501,
    fTimeZoneName: "Chatham Standard Time",
    fTimeZoneAbbrev: "CHAST",
    fOffset: 12.75,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 2601,
    fTimeZoneName: "Clipperton Island Standard Time",
    fTimeZoneAbbrev: "CIST",
    fOffset: -8,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 2701,
    fTimeZoneName: "Cook Island Time",
    fTimeZoneAbbrev: "CKT",
    fOffset: -10,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 2801,
    fTimeZoneName: "Chile Standard Time",
    fTimeZoneAbbrev: "CLT",
    fOffset: -4,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 2802,
    fTimeZoneName: "Chile Summer Time",
    fTimeZoneAbbrev: "CLST",
    fOffset: -3,
    fStandardTime: 0,
  },
  {
    fTimeZoneID: 2901,
    fTimeZoneName: "Cuba Standard Time",
    fTimeZoneAbbrev: "CST",
    fOffset: -5,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 2902,
    fTimeZoneName: "Cuba Daylight Time",
    fTimeZoneAbbrev: "CDT",
    fOffset: -4,
    fStandardTime: 0,
  },
  {
    fTimeZoneID: 3001,
    fTimeZoneName: "Central Standard Time (North America)",
    fTimeZoneAbbrev: "CST",
    fOffset: -6,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 3002,
    fTimeZoneName: "Central Daylight Time",
    fTimeZoneAbbrev: "CDT",
    fOffset: -5,
    fStandardTime: 0,
  },
  {
    fTimeZoneID: 3101,
    fTimeZoneName: "China Standard Time",
    fTimeZoneAbbrev: "CST",
    fOffset: 8,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 3201,
    fTimeZoneName: "Central Standard Time (Australia)",
    fTimeZoneAbbrev: "CST",
    fOffset: 9.5,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 3301,
    fTimeZoneName: "China Time",
    fTimeZoneAbbrev: "CT",
    fOffset: 8,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 3401,
    fTimeZoneName: "Cape Verde Time",
    fTimeZoneAbbrev: "CVT",
    fOffset: -1,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 3501,
    fTimeZoneName: "Christmas Island Time",
    fTimeZoneAbbrev: "CXT",
    fOffset: 7,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 3601,
    fTimeZoneName: "Chamorro Standard Time",
    fTimeZoneAbbrev: "CHST",
    fOffset: 10,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 3701,
    fTimeZoneName: "AIX specific equivalent of Central European Time",
    fTimeZoneAbbrev: "DFT",
    fOffset: 1,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 3801,
    fTimeZoneName: "Easter Island Standard Time",
    fTimeZoneAbbrev: "EAST",
    fOffset: -6,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 3802,
    fTimeZoneName: "Easter Island Summer Time",
    fTimeZoneAbbrev: "EASST",
    fOffset: -5,
    fStandardTime: 0,
  },
  {
    fTimeZoneID: 3901,
    fTimeZoneName: "East Africa Time",
    fTimeZoneAbbrev: "EAT",
    fOffset: 3,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 4001,
    fTimeZoneName: "Eastern Caribbean Time (does not recognise DST)",
    fTimeZoneAbbrev: "ECT",
    fOffset: -4,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 4101,
    fTimeZoneName: "Ecuador Time",
    fTimeZoneAbbrev: "ECT",
    fOffset: -5,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 4201,
    fTimeZoneName: "Eastern European Time",
    fTimeZoneAbbrev: "EET",
    fOffset: 2,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 4202,
    fTimeZoneName: "Eastern European Summer Time",
    fTimeZoneAbbrev: "EEST",
    fOffset: 3,
    fStandardTime: 0,
  },
  {
    fTimeZoneID: 4301,
    fTimeZoneName: "Eastern Standard Time (North America)",
    fTimeZoneAbbrev: "EST",
    fOffset: -5,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 4302,
    fTimeZoneName: "Eastern Daylight Time",
    fTimeZoneAbbrev: "EDT",
    fOffset: -4,
    fStandardTime: 0,
  },
  {
    fTimeZoneID: 4401,
    fTimeZoneName: "Fiji Time",
    fTimeZoneAbbrev: "FJT",
    fOffset: 12,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 4402,
    fTimeZoneName: "Fiji Summer Time",
    fTimeZoneAbbrev: "FJST",
    fOffset: 13,
    fStandardTime: 0,
  },
  {
    fTimeZoneID: 4501,
    fTimeZoneName: "Falkland Islands Time",
    fTimeZoneAbbrev: "FKT",
    fOffset: -4,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 4601,
    fTimeZoneName: "Galapagos Time",
    fTimeZoneAbbrev: "GALT",
    fOffset: -6,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 4701,
    fTimeZoneName: "Georgia Standard Time",
    fTimeZoneAbbrev: "GET",
    fOffset: 4,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 4801,
    fTimeZoneName: "French Guiana Time",
    fTimeZoneAbbrev: "GFT",
    fOffset: -3,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 4901,
    fTimeZoneName: "Gilbert Island Time",
    fTimeZoneAbbrev: "GILT",
    fOffset: 12,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 5001,
    fTimeZoneName: "Gambier Island Time",
    fTimeZoneAbbrev: "GIT",
    fOffset: -9,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 5101,
    fTimeZoneName: "Greenwich Mean Time",
    fTimeZoneAbbrev: "GMT",
    fOffset: 0,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 5102,
    fTimeZoneName: "British Summer Time",
    fTimeZoneAbbrev: "BST",
    fOffset: 1,
    fStandardTime: 0,
  },
  {
    fTimeZoneID: 5103,
    fTimeZoneName: "Irish Standard Time",
    fTimeZoneAbbrev: "IST",
    fOffset: 1,
    fStandardTime: 0,
  },
  {
    fTimeZoneID: 5201,
    fTimeZoneName: "South Georgia and the South Sandwich Islands",
    fTimeZoneAbbrev: "GST",
    fOffset: -2,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 5301,
    fTimeZoneName: "Gulf Standard Time",
    fTimeZoneAbbrev: "GST",
    fOffset: 4,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 5401,
    fTimeZoneName: "Guyana Time",
    fTimeZoneAbbrev: "GYT",
    fOffset: -4,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 5501,
    fTimeZoneName: "Heure Avancée d'Europe Centrale francised name for CEST",
    fTimeZoneAbbrev: "HAEC",
    fOffset: 2,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 5601,
    fTimeZoneName: "Hawaii-Aleutian Standard Time",
    fTimeZoneAbbrev: "HAST",
    fOffset: -10,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 5701,
    fTimeZoneName: "Hong Kong Time",
    fTimeZoneAbbrev: "HKT",
    fOffset: 8,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 5801,
    fTimeZoneName: "Heard and McDonald Islands Time",
    fTimeZoneAbbrev: "HMT",
    fOffset: 5,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 5901,
    fTimeZoneName: "Hawaii Standard Time",
    fTimeZoneAbbrev: "HST",
    fOffset: -10,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 6001,
    fTimeZoneName: "Indochina Time",
    fTimeZoneAbbrev: "ICT",
    fOffset: 7,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 6101,
    fTimeZoneName: "Irkutsk Time",
    fTimeZoneAbbrev: "IRKT",
    fOffset: 9,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 6201,
    fTimeZoneName: "Iran Standard Time",
    fTimeZoneAbbrev: "IRST",
    fOffset: 3.5,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 6202,
    fTimeZoneName: "Iran Daylight Time",
    fTimeZoneAbbrev: "IRDT",
    fOffset: 4.5,
    fStandardTime: 0,
  },
  {
    fTimeZoneID: 6301,
    fTimeZoneName: "Indian Standard Time",
    fTimeZoneAbbrev: "IST",
    fOffset: 5.5,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 6401,
    fTimeZoneName: "Israel Standard Time",
    fTimeZoneAbbrev: "IST",
    fOffset: 2,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 6402,
    fTimeZoneName: "Israel Daylight Time",
    fTimeZoneAbbrev: "IDT",
    fOffset: 3,
    fStandardTime: 0,
  },
  {
    fTimeZoneID: 6501,
    fTimeZoneName: "Japan Standard Time",
    fTimeZoneAbbrev: "JST",
    fOffset: 9,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 6601,
    fTimeZoneName: "Krasnoyarsk Time",
    fTimeZoneAbbrev: "KRAT",
    fOffset: 8,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 6701,
    fTimeZoneName: "Korea Standard Time",
    fTimeZoneAbbrev: "KST",
    fOffset: 9,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 6801,
    fTimeZoneName: "Lord Howe Standard Time",
    fTimeZoneAbbrev: "LHST",
    fOffset: 10.5,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 6901,
    fTimeZoneName: "Line Islands Time",
    fTimeZoneAbbrev: "LINT",
    fOffset: 14,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 7001,
    fTimeZoneName: "Magadan Time",
    fTimeZoneAbbrev: "MAGT",
    fOffset: 11,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 7101,
    fTimeZoneName: "Middle European Time Same zone as CET",
    fTimeZoneAbbrev: "MET",
    fOffset: 2,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 7201,
    fTimeZoneName: "Marquesas Islands Time",
    fTimeZoneAbbrev: "MIT",
    fOffset: -9.5,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 7301,
    fTimeZoneName: "Moscow Standard Time",
    fTimeZoneAbbrev: "MSK",
    fOffset: 4,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 7401,
    fTimeZoneName: "Malaysian Standard Time",
    fTimeZoneAbbrev: "MST",
    fOffset: 8,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 7501,
    fTimeZoneName: "Mountain Standard Time (North America)",
    fTimeZoneAbbrev: "MST",
    fOffset: -7,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 7502,
    fTimeZoneName: "Mountain Daylight Time",
    fTimeZoneAbbrev: "MDT",
    fOffset: -6,
    fStandardTime: 0,
  },
  {
    fTimeZoneID: 7601,
    fTimeZoneName: "Myanmar Standard Time",
    fTimeZoneAbbrev: "MST",
    fOffset: 6.5,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 7701,
    fTimeZoneName: "Mauritius Time",
    fTimeZoneAbbrev: "MUT",
    fOffset: 4,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 7801,
    fTimeZoneName: "Malaysia Time",
    fTimeZoneAbbrev: "MYT",
    fOffset: 8,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 7901,
    fTimeZoneName: "Norfolk Time[1]",
    fTimeZoneAbbrev: "NFT",
    fOffset: 11.5,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 8001,
    fTimeZoneName: "Nepal Time",
    fTimeZoneAbbrev: "NPT",
    fOffset: 5.75,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 8101,
    fTimeZoneName: "Newfoundland Standard Time",
    fTimeZoneAbbrev: "NST",
    fOffset: -3.5,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 8102,
    fTimeZoneName: "Newfoundland Daylight Time",
    fTimeZoneAbbrev: "NDT",
    fOffset: -2,
    fStandardTime: 0,
  },
  {
    fTimeZoneID: 8201,
    fTimeZoneName: "New Zealand Standard Time",
    fTimeZoneAbbrev: "NZST",
    fOffset: 12,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 8202,
    fTimeZoneName: "New Zealand Daylight Time",
    fTimeZoneAbbrev: "NZDT",
    fOffset: 13,
    fStandardTime: 0,
  },
  {
    fTimeZoneID: 8301,
    fTimeZoneName: "Omsk Standard Time",
    fTimeZoneAbbrev: "OMST",
    fOffset: 7,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 8401,
    fTimeZoneName: "Kamchatka Time",
    fTimeZoneAbbrev: "PETT",
    fOffset: 12,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 8501,
    fTimeZoneName: "Phoenix Island Time",
    fTimeZoneAbbrev: "PHOT",
    fOffset: 13,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 8601,
    fTimeZoneName: "Pakistan Standard Time",
    fTimeZoneAbbrev: "PKT",
    fOffset: 5,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 8701,
    fTimeZoneName: "Pacific Standard Time (North America)",
    fTimeZoneAbbrev: "PST",
    fOffset: -8,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 8702,
    fTimeZoneName: "Pacific Daylight Time",
    fTimeZoneAbbrev: "PDT",
    fOffset: -7,
    fStandardTime: 0,
  },
  {
    fTimeZoneID: 8801,
    fTimeZoneName: "Philippine Standard Time",
    fTimeZoneAbbrev: "PST",
    fOffset: 8,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 8901,
    fTimeZoneName: "Réunion Time",
    fTimeZoneAbbrev: "RET",
    fOffset: 4,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 9001,
    fTimeZoneName: "Samara Time",
    fTimeZoneAbbrev: "SAMT",
    fOffset: 4,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 9101,
    fTimeZoneName: "South African Standard Time",
    fTimeZoneAbbrev: "SAST",
    fOffset: 2,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 9201,
    fTimeZoneName: "Solomon Islands Time",
    fTimeZoneAbbrev: "SBT",
    fOffset: 11,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 9301,
    fTimeZoneName: "Seychelles Time",
    fTimeZoneAbbrev: "SCT",
    fOffset: 4,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 9401,
    fTimeZoneName: "Singapore Time",
    fTimeZoneAbbrev: "SGT",
    fOffset: 8,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 9501,
    fTimeZoneName: "Sri Lanka Time",
    fTimeZoneAbbrev: "SLT",
    fOffset: 5.5,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 9601,
    fTimeZoneName: "Samoa Standard Time",
    fTimeZoneAbbrev: "SST",
    fOffset: 13,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 9602,
    fTimeZoneName: "West Samoa Summer Time",
    fTimeZoneAbbrev: "WSST",
    fOffset: 14,
    fStandardTime: 0,
  },
  {
    fTimeZoneID: 9701,
    fTimeZoneName: "Singapore Standard Time",
    fTimeZoneAbbrev: "SST",
    fOffset: 8,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 9801,
    fTimeZoneName: "Tahiti Time",
    fTimeZoneAbbrev: "TAHT",
    fOffset: -10,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 9901,
    fTimeZoneName: "Thailand Standard Time",
    fTimeZoneAbbrev: "THA",
    fOffset: 7,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 10001,
    fTimeZoneName: "Coordinated Universal Time",
    fTimeZoneAbbrev: "UTC",
    fOffset: 0,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 10101,
    fTimeZoneName: "Uruguay Standard Time",
    fTimeZoneAbbrev: "UYT",
    fOffset: -3,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 10102,
    fTimeZoneName: "Uruguay Summer Time",
    fTimeZoneAbbrev: "UYST",
    fOffset: -2,
    fStandardTime: 0,
  },
  {
    fTimeZoneID: 10201,
    fTimeZoneName: "Venezuelan Standard Time",
    fTimeZoneAbbrev: "VET",
    fOffset: -4.5,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 10301,
    fTimeZoneName: "Vladivostok Time",
    fTimeZoneAbbrev: "VLAT",
    fOffset: 11,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 10401,
    fTimeZoneName: "West Africa Time",
    fTimeZoneAbbrev: "WAT",
    fOffset: 1,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 10402,
    fTimeZoneName: "West Africa Summer Time",
    fTimeZoneAbbrev: "WAST",
    fOffset: 2,
    fStandardTime: 0,
  },
  {
    fTimeZoneID: 10501,
    fTimeZoneName: "Western European Time",
    fTimeZoneAbbrev: "WET",
    fOffset: 0,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 10502,
    fTimeZoneName: "Western European Summer Time",
    fTimeZoneAbbrev: "WEST",
    fOffset: 1,
    fStandardTime: 0,
  },
  {
    fTimeZoneID: 10601,
    fTimeZoneName: "Western Standard Time",
    fTimeZoneAbbrev: "WST",
    fOffset: 8,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 10701,
    fTimeZoneName: "Yakutsk Time",
    fTimeZoneAbbrev: "YAKT",
    fOffset: 10,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 10801,
    fTimeZoneName: "Yekaterinburg Time",
    fTimeZoneAbbrev: "YEKT",
    fOffset: 6,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 10901,
    fTimeZoneName: "Western Sahara Standard Time",
    fTimeZoneAbbrev: "WT",
    fOffset: 0,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 10902,
    fTimeZoneName: "Western Sahara Summer Time",
    fTimeZoneAbbrev: "WST",
    fOffset: 1,
    fStandardTime: 0,
  },
  {
    fTimeZoneID: 11001,
    fTimeZoneName: "Eastern Greenland Time",
    fTimeZoneAbbrev: "EGT",
    fOffset: 1,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 11002,
    fTimeZoneName: "Eastern Greenland Summer Time",
    fTimeZoneAbbrev: "EGST",
    fOffset: 0,
    fStandardTime: 0,
  },
  {
    fTimeZoneID: 11101,
    fTimeZoneName: "West Greenland Time",
    fTimeZoneAbbrev: "WGT",
    fOffset: 3,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 11102,
    fTimeZoneName: "Western Greenland Summer Time",
    fTimeZoneAbbrev: "WGST",
    fOffset: -2,
    fStandardTime: 0,
  },
  {
    fTimeZoneID: 11201,
    fTimeZoneName: "Amazon Time",
    fTimeZoneAbbrev: "AMT",
    fOffset: -4,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 11202,
    fTimeZoneName: "Ulaanbaatar Daylight Time",
    fTimeZoneAbbrev: "ULAST",
    fOffset: 9,
    fStandardTime: 0,
  },
  {
    fTimeZoneID: 11301,
    fTimeZoneName: "Colombia Time",
    fTimeZoneAbbrev: "COT",
    fOffset: -22,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 11401,
    fTimeZoneName: "Bolivia Time",
    fTimeZoneAbbrev: "BOT",
    fOffset: -4,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 11501,
    fTimeZoneName: "Central Indonesian Time",
    fTimeZoneAbbrev: "WITA",
    fOffset: 8,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 11601,
    fTimeZoneName: "Eastern Indonesian Time",
    fTimeZoneAbbrev: "WIT",
    fOffset: 9,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 11701,
    fTimeZoneName: "Western Indonesian Time",
    fTimeZoneAbbrev: "WIB",
    fOffset: 7,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 11801,
    fTimeZoneName: "Peru Time",
    fTimeZoneAbbrev: "PET",
    fOffset: -5,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 11901,
    fTimeZoneName: "Philippine Time",
    fTimeZoneAbbrev: "PHT",
    fOffset: 8,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 12001,
    fTimeZoneName: "Vanuatu Time",
    fTimeZoneAbbrev: "VUT",
    fOffset: 11,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 12101,
    fTimeZoneName: "Hovd Time",
    fTimeZoneAbbrev: "HOVT",
    fOffset: 7,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 12201,
    fTimeZoneName: "Ulaanbaatar Time",
    fTimeZoneAbbrev: "ULAT",
    fOffset: 8,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 12301,
    fTimeZoneName: "Tonga Time",
    fTimeZoneAbbrev: "TOT",
    fOffset: 13,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 12401,
    fTimeZoneName: "Further-eastern European Time",
    fTimeZoneAbbrev: "FET",
    fOffset: 3,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 12501,
    fTimeZoneName: "Uzbekistan Time",
    fTimeZoneAbbrev: "UZT",
    fOffset: 5,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 12601,
    fTimeZoneName: "Tajikistan Time",
    fTimeZoneAbbrev: "TJT",
    fOffset: 5,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 12701,
    fTimeZoneName: "Suriname Time",
    fTimeZoneAbbrev: "SRT",
    fOffset: -3,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 12801,
    fTimeZoneName: "Brunei Darussalam Time",
    fTimeZoneAbbrev: "BNT",
    fOffset: 8,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 12901,
    fTimeZoneName: "Maldives Time",
    fTimeZoneAbbrev: "MVT",
    fOffset: 5,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 13001,
    fTimeZoneName: "Central Western Standard Time",
    fTimeZoneAbbrev: "CWST",
    fOffset: 8.75,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 13101,
    fTimeZoneName: "Oral Time",
    fTimeZoneAbbrev: "ORAT",
    fOffset: 5,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 13201,
    fTimeZoneName: "Qyzylorda Time",
    fTimeZoneAbbrev: "QYZT",
    fOffset: 6,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 13301,
    fTimeZoneName: "Kyrgyzstan Time",
    fTimeZoneAbbrev: "KGT",
    fOffset: 6,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 13401,
    fTimeZoneName: "Anadyr Time",
    fTimeZoneAbbrev: "ANAT",
    fOffset: 12,
    fStandardTime: 1,
  },
  {
    fTimeZoneID: 13501,
    fTimeZoneName: "Azores Time",
    fTimeZoneAbbrev: "AZOT",
    fOffset: -1,
    fStandardTime: 1,
  },
];
